// dummyData.js

const dummyNewsfeedData = [
    {
      title: "Breaking News: Lorem Ipsum Dolor Sit Amet",
      feedname: "News Source 1",
      date: "2023-09-12",
      summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      link: "https://example.com/news/article1",
      icon: "news1",
    },
    {
      title: "Tech News: Fusce Eget Sapien Aenean Sit Amet",
      feedname: "Tech Gazette",
      date: "2023-09-11",
      summary: "Fusce eget sapien aenean sit amet rhoncus orci.",
      link: "https://example.com/news/article2",
      icon: "tech1",
    },
    // Add more newsfeed items as needed
    {
      title: "Breaking News: Lorem Ipsum Dolor Sit Amet",
      feedname: "News Source 1",
      date: "2023-09-12",
      summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      link: "https://example.com/news/article1",
      icon: "news1",
    },
    {
      title: "Tech News: Fusce Eget Sapien Aenean Sit Amet",
      feedname: "Tech Gazette",
      date: "2023-09-11",
      summary: "Fusce eget sapien aenean sit amet rhoncus orci.",
      link: "https://example.com/news/article2",
      icon: "tech1",
    },
    // Add more newsfeed items as needed
    {
      title: "Breaking News: Lorem Ipsum Dolor Sit Amet",
      feedname: "News Source 1",
      date: "2023-09-12",
      summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      link: "https://example.com/news/article1",
      icon: "news1",
    },
    {
      title: "Tech News: Fusce Eget Sapien Aenean Sit Amet",
      feedname: "Tech Gazette",
      date: "2023-09-11",
      summary: "Fusce eget sapien aenean sit amet rhoncus orci.",
      link: "https://example.com/news/article2",
      icon: "tech1",
    },
    // Add more newsfeed items as needed
    {
      title: "Breaking News: Lorem Ipsum Dolor Sit Amet",
      feedname: "News Source 1",
      date: "2023-09-12",
      summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      link: "https://example.com/news/article1",
      icon: "news1",
    },
    {
      title: "Tech News: Fusce Eget Sapien Aenean Sit Amet",
      feedname: "Tech Gazette",
      date: "2023-09-11",
      summary: "Fusce eget sapien aenean sit amet rhoncus orci.",
      link: "https://example.com/news/article2",
      icon: "tech1",
    },
    // Add more newsfeed items as needed
    {
      title: "Breaking News: Lorem Ipsum Dolor Sit Amet",
      feedname: "News Source 1",
      date: "2023-09-12",
      summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      link: "https://example.com/news/article1",
      icon: "news1",
    },
    {
      title: "Tech News: Fusce Eget Sapien Aenean Sit Amet",
      feedname: "Tech Gazette",
      date: "2023-09-11",
      summary: "Fusce eget sapien aenean sit amet rhoncus orci.",
      link: "https://example.com/news/article2",
      icon: "tech1",
    },
    // Add more newsfeed items as needed
    {
      title: "Breaking News: Lorem Ipsum Dolor Sit Amet",
      feedname: "News Source 1",
      date: "2023-09-12",
      summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      link: "https://example.com/news/article1",
      icon: "news1",
    },
    {
      title: "Tech News: Fusce Eget Sapien Aenean Sit Amet",
      feedname: "Tech Gazette",
      date: "2023-09-11",
      summary: "Fusce eget sapien aenean sit amet rhoncus orci.",
      link: "https://example.com/news/article2",
      icon: "tech1",
    },
    // Add more newsfeed items as needed
    {
      title: "Breaking News: Lorem Ipsum Dolor Sit Amet",
      feedname: "News Source 1",
      date: "2023-09-12",
      summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      link: "https://example.com/news/article1",
      icon: "news1",
    },
    {
      title: "Tech News: Fusce Eget Sapien Aenean Sit Amet",
      feedname: "Tech Gazette",
      date: "2023-09-11",
      summary: "Fusce eget sapien aenean sit amet rhoncus orci.",
      link: "https://example.com/news/article2",
      icon: "tech1",
    },
    // Add more newsfeed items as needed
    {
      title: "Breaking News: Lorem Ipsum Dolor Sit Amet",
      feedname: "News Source 1",
      date: "2023-09-12",
      summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      link: "https://example.com/news/article1",
      icon: "news1",
    },
    {
      title: "Tech News: Fusce Eget Sapien Aenean Sit Amet",
      feedname: "Tech Gazette",
      date: "2023-09-11",
      summary: "Fusce eget sapien aenean sit amet rhoncus orci.",
      link: "https://example.com/news/article2",
      icon: "tech1",
    },
    // Add more newsfeed items as needed
    {
      title: "Breaking News: Lorem Ipsum Dolor Sit Amet",
      feedname: "News Source 1",
      date: "2023-09-12",
      summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      link: "https://example.com/news/article1",
      icon: "news1",
    },
    {
      title: "Tech News: Fusce Eget Sapien Aenean Sit Amet",
      feedname: "Tech Gazette",
      date: "2023-09-11",
      summary: "Fusce eget sapien aenean sit amet rhoncus orci.",
      link: "https://example.com/news/article2",
      icon: "tech1",
    },
    // Add more newsfeed items as needed
    {
      title: "Breaking News: Lorem Ipsum Dolor Sit Amet",
      feedname: "News Source 1",
      date: "2023-09-12",
      summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      link: "https://example.com/news/article1",
      icon: "news1",
    },
    {
      title: "Tech News: Fusce Eget Sapien Aenean Sit Amet",
      feedname: "Tech Gazette",
      date: "2023-09-11",
      summary: "Fusce eget sapien aenean sit amet rhoncus orci.",
      link: "https://example.com/news/article2",
      icon: "tech1",
    },
    // Add more newsfeed items as needed
    {
      title: "Breaking News: Lorem Ipsum Dolor Sit Amet",
      feedname: "News Source 1",
      date: "2023-09-12",
      summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      link: "https://example.com/news/article1",
      icon: "news1",
    },
    {
      title: "Tech News: Fusce Eget Sapien Aenean Sit Amet",
      feedname: "Tech Gazette",
      date: "2023-09-11",
      summary: "Fusce eget sapien aenean sit amet rhoncus orci.",
      link: "https://example.com/news/article2",
      icon: "tech1",
    },
    // Add more newsfeed items as needed
    {
      title: "Breaking News: Lorem Ipsum Dolor Sit Amet",
      feedname: "News Source 1",
      date: "2023-09-12",
      summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      link: "https://example.com/news/article1",
      icon: "news1",
    },
    {
      title: "Tech News: Fusce Eget Sapien Aenean Sit Amet",
      feedname: "Tech Gazette",
      date: "2023-09-11",
      summary: "Fusce eget sapien aenean sit amet rhoncus orci.",
      link: "https://example.com/news/article2",
      icon: "tech1",
    },
    // Add more newsfeed items as needed
    {
      title: "Breaking News: Lorem Ipsum Dolor Sit Amet",
      feedname: "News Source 1",
      date: "2023-09-12",
      summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      link: "https://example.com/news/article1",
      icon: "news1",
    },
    {
      title: "Tech News: Fusce Eget Sapien Aenean Sit Amet",
      feedname: "Tech Gazette",
      date: "2023-09-11",
      summary: "Fusce eget sapien aenean sit amet rhoncus orci.",
      link: "https://example.com/news/article2",
      icon: "tech1",
    },
    // Add more newsfeed items as needed
    {
      title: "Breaking News: Lorem Ipsum Dolor Sit Amet",
      feedname: "News Source 1",
      date: "2023-09-12",
      summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      link: "https://example.com/news/article1",
      icon: "news1",
    },
    {
      title: "Tech News: Fusce Eget Sapien Aenean Sit Amet",
      feedname: "Tech Gazette",
      date: "2023-09-11",
      summary: "Fusce eget sapien aenean sit amet rhoncus orci.",
      link: "https://example.com/news/article2",
      icon: "tech1",
    },
    // Add more newsfeed items as needed
    {
      title: "Breaking News: Lorem Ipsum Dolor Sit Amet",
      feedname: "News Source 1",
      date: "2023-09-12",
      summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      link: "https://example.com/news/article1",
      icon: "news1",
    },
    {
      title: "Tech News: Fusce Eget Sapien Aenean Sit Amet",
      feedname: "Tech Gazette",
      date: "2023-09-11",
      summary: "Fusce eget sapien aenean sit amet rhoncus orci.",
      link: "https://example.com/news/article2",
      icon: "tech1",
    },
    // Add more newsfeed items as needed
    {
      title: "Breaking News: Lorem Ipsum Dolor Sit Amet",
      feedname: "News Source 1",
      date: "2023-09-12",
      summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      link: "https://example.com/news/article1",
      icon: "news1",
    },
    {
      title: "Tech News: Fusce Eget Sapien Aenean Sit Amet",
      feedname: "Tech Gazette",
      date: "2023-09-11",
      summary: "Fusce eget sapien aenean sit amet rhoncus orci.",
      link: "https://example.com/news/article2",
      icon: "tech1",
    },
    // Add more newsfeed items as needed
    {
      title: "Breaking News: Lorem Ipsum Dolor Sit Amet",
      feedname: "News Source 1",
      date: "2023-09-12",
      summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      link: "https://example.com/news/article1",
      icon: "news1",
    },
    {
      title: "Tech News: Fusce Eget Sapien Aenean Sit Amet",
      feedname: "Tech Gazette",
      date: "2023-09-11",
      summary: "Fusce eget sapien aenean sit amet rhoncus orci.",
      link: "https://example.com/news/article2",
      icon: "tech1",
    },
    // Add more newsfeed items as needed
    {
      title: "Breaking News: Lorem Ipsum Dolor Sit Amet",
      feedname: "News Source 1",
      date: "2023-09-12",
      summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      link: "https://example.com/news/article1",
      icon: "news1",
    },
    {
      title: "Tech News: Fusce Eget Sapien Aenean Sit Amet",
      feedname: "Tech Gazette",
      date: "2023-09-11",
      summary: "Fusce eget sapien aenean sit amet rhoncus orci.",
      link: "https://example.com/news/article2",
      icon: "tech1",
    },
    // Add more newsfeed items as needed
    {
      title: "Breaking News: Lorem Ipsum Dolor Sit Amet",
      feedname: "News Source 1",
      date: "2023-09-12",
      summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      link: "https://example.com/news/article1",
      icon: "news1",
    },
    {
      title: "Tech News: Fusce Eget Sapien Aenean Sit Amet",
      feedname: "Tech Gazette",
      date: "2023-09-11",
      summary: "Fusce eget sapien aenean sit amet rhoncus orci.",
      link: "https://example.com/news/article2",
      icon: "tech1",
    },
    // Add more newsfeed items as needed
  ];
  
  module.exports = {
    dummyNewsfeedData,
  };
  